"""User Table Upated

Revision ID: 14d060d1fb56
Revises: a31d7f2b6039
Create Date: 2026-03-22 11:51:11.209423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d060d1fb56'
down_revision: Union[str, Sequence[str], None] = 'a31d7f2b6039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_location_points_geom_gist'), table_name='location_points', postgresql_using='gist')
    op.drop_index(op.f('idx_territories_polygon_gist'), table_name='territories', postgresql_using='gist')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    # Set default values for existing users
    op.execute("UPDATE users SET name = SPLIT_PART(email, '@', 1) WHERE name IS NULL")
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    # Now make name not null
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'name')
    op.create_index(op.f('idx_territories_polygon_gist'), 'territories', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_location_points_geom_gist'), 'location_points', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###