"""Add activity and territory tables

Revision ID: a31d7f2b6039
Revises: d1d8f6d914e2
Create Date: 2026-03-13 18:28:16.961979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'a31d7f2b6039'
down_revision: Union[str, Sequence[str], None] = 'd1d8f6d914e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('walk', 'run', 'cycle', name='activitytype'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_sessions_id'), 'activity_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_user_id'), 'activity_sessions', ['user_id'], unique=False)
    op.create_table('location_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location_points_geom_gist', 'location_points', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_location_points_id'), 'location_points', ['id'], unique=False)
    op.create_index(op.f('ix_location_points_session_id'), 'location_points', ['session_id'], unique=False)
    op.create_table('territories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_territories_polygon_gist', 'territories', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_territories_id'), 'territories', ['id'], unique=False)
    op.create_index(op.f('ix_territories_owner_id'), 'territories', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_territories_owner_id'), table_name='territories')
    op.drop_index(op.f('ix_territories_id'), table_name='territories')
    op.drop_index('idx_territories_polygon_gist', table_name='territories', postgresql_using='gist')
    op.drop_table('territories')
    op.drop_index(op.f('ix_location_points_session_id'), table_name='location_points')
    op.drop_index(op.f('ix_location_points_id'), table_name='location_points')
    op.drop_index('idx_location_points_geom', table_name='location_points', postgresql_using='gist')
    op.drop_table('location_points')
    op.drop_index(op.f('ix_activity_sessions_user_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_id'), table_name='activity_sessions')
    op.drop_table('activity_sessions')
    # ### end Alembic commands ###
