"""Auth table updated

Revision ID: d1d8f6d914e2
Revises: d8c3f4b5a6e7
Create Date: 2026-03-11 23:51:53.369427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d8f6d914e2'
down_revision: Union[str, Sequence[str], None] = 'd8c3f4b5a6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_expires_at')
    op.drop_column('users', 'reset_password_token_hash')
    # ### end Alembic commands ###
